### ISSUE TITLE
Suggestion: change "blacklist" to "deny list"

### ISSUE THREAD

**Issue by FitzFrobozz** [RyotaUshio/obsidian-command-block-list#1]
Given the connotations terms like "blacklist" and "whitelist" have, this is a simple suggestion to replace the term in the plugin name and description with "deny list", or some other racially-neutral term. Thanks for your consideration!

**Comment by RyotaUshio** [comment]
Hi, thank you for pointing it out. I didn't realize the term can have such a racial implication.
I'm happy to update the plugin name to something more appropriate.

I'm sorry if you are offended by the name.

**Comment by RyotaUshio** [comment]
I've renamed it "Command Block List".

**Comment by FitzFrobozz** [comment]
That's great! And I wasn't offended at all. Appreciate the quick response.
